"""
End-to-end integration test for CliApp with DemoBackend.

Tests the full pipeline: domain config loading, testset loading, specification
finding, test execution, and report generation. Two domains are executed
concurrently on the same storage to test for concurrency issues.

Test design leverages deliberate data quality issues in prepare_demo_data.py:
  - payments: transactions_2 is truncated by half during staging load,
    causing a stagecount mismatch (NOK).
  - sales: core_customer_transactions filters out africa region,
    causing a compare mismatch (NOK).

Demo artifacts (specs, configs, testsets) are generated by
prepare_demo_artifacts.py and read from disk via LocalUserStorage.
"""

import concurrent.futures
from pathlib import Path


from src.apps.cli_app import CliApp
from src.apps.cli_di import CliDependencyInjector
from src.config import Config
from src.domain_ports import SaveTestSetCommand
from src.dtos import (
    DomainConfigDTO,
    TestResult,
    TestSetDTO,
    TestStatus,
    TestType,
)
from tests.fixtures.demo.prepare_demo_data import prepare_demo_data
from tests.fixtures.demo.prepare_demo_artifacts import (
    prepare_demo_artifacts,
    clean_up_demo_artifacts,
)


# All demo data (DWH + artifacts) lives in one directory
_DEMO_DIR = Path(__file__).parent / "_demo_data"


class TestCliAppE2E:
    def test_concurrent_execution_of_two_domains(self):
        # --- Setup: prepare everything in _DEMO_DIR ---
        clean_up_demo_artifacts(_DEMO_DIR)
        prepare_demo_data(_DEMO_DIR)
        prepare_demo_artifacts(_DEMO_DIR)

        try:
            self._run_test()
        finally:
            clean_up_demo_artifacts(_DEMO_DIR)

    def _run_test(self):
        # --- Configure app to use local storage and demo backend ---
        config = Config(
            DATATESTER_DATA_PLATFORM="DEMO",
            DATATESTER_USER_STORAGE_ENGINE="LOCAL",
            DATATESTER_INTERNAL_STORAGE_LOCATION=(f"local://{_DEMO_DIR}/internal/"),
            DATATESTER_DEMO_RAW_PATH=str(_DEMO_DIR / "raw"),
            DATATESTER_DEMO_DB_PATH=str(_DEMO_DIR / "dbs"),
        )
        di = CliDependencyInjector(config)

        # Load domain configs from persisted JSONs
        dc_driver = di.domain_config_driver()
        configs_dir = _DEMO_DIR / "configs"
        for cfg_file in sorted(configs_dir.glob("*.json")):
            dto = DomainConfigDTO.from_json(cfg_file.read_text())
            dc_driver.save_domain_config(config=dto)

        # Load testsets from persisted JSONs
        ts_driver = di.testset_driver()
        testsets_dir = _DEMO_DIR / "testsets"
        for ts_file in sorted(testsets_dir.rglob("*.json")):
            dto = TestSetDTO.from_json(ts_file.read_text())
            ts_driver.adapter.save_testset(
                SaveTestSetCommand(testset=dto),
            )

        # --- Concurrent execution ---
        app1 = CliApp(config)
        app2 = CliApp(config)

        with concurrent.futures.ThreadPoolExecutor(max_workers=2) as ex:
            f1 = ex.submit(app1.run_tests, "payments", "payments_full")
            f2 = ex.submit(app2.run_tests, "sales", "sales_validation")
            f1.result(timeout=120)
            f2.result(timeout=120)

        # --- Verify using fresh DI ---
        verify_di = CliDependencyInjector(config)

        # 1. Testruns persisted
        tr_driver = verify_di.testrun_driver()
        payments_trs = tr_driver.list_testruns(domain="payments")
        sales_trs = tr_driver.list_testruns(domain="sales")
        assert len(payments_trs) == 1
        assert len(sales_trs) == 1

        # 2. Payments testrun: 6 testcases, overall NOK
        #    NOK because stage_transactions STAGECOUNT fails (truncated txn_2)
        payments_tr = payments_trs[0]
        assert len(payments_tr.testcase_results) == 6
        assert payments_tr.result == TestResult.NOK
        assert payments_tr.status == TestStatus.FINISHED

        pr = {
            (tc.testobject.name, tc.testtype): tc for tc in payments_tr.testcase_results
        }
        assert pr[("stage_accounts", TestType.SCHEMA)].result == TestResult.OK
        assert pr[("stage_transactions", TestType.SCHEMA)].result == TestResult.OK
        assert pr[("core_account_payments", TestType.ROWCOUNT)].result == TestResult.OK
        assert pr[("core_account_payments", TestType.COMPARE)].result == TestResult.OK
        assert pr[("stage_accounts", TestType.STAGECOUNT)].result == TestResult.OK
        assert pr[("stage_transactions", TestType.STAGECOUNT)].result == TestResult.NOK
        for tc in payments_tr.testcase_results:
            assert tc.status == TestStatus.FINISHED

        # 3. Sales testrun: 6 testcases, overall NOK
        #    NOK because core_customer_transactions COMPARE fails (africa)
        sales_tr = sales_trs[0]
        assert len(sales_tr.testcase_results) == 6
        assert sales_tr.result == TestResult.NOK
        assert sales_tr.status == TestStatus.FINISHED

        sr = {(tc.testobject.name, tc.testtype): tc for tc in sales_tr.testcase_results}
        assert sr[("stage_customers", TestType.SCHEMA)].result == TestResult.OK
        assert sr[("stage_transactions", TestType.SCHEMA)].result == TestResult.OK
        assert (
            sr[("core_customer_transactions", TestType.ROWCOUNT)].result == TestResult.OK
        )
        assert (
            sr[("core_customer_transactions", TestType.COMPARE)].result == TestResult.NOK
        )
        assert sr[("stage_customers", TestType.STAGECOUNT)].result == TestResult.OK
        assert sr[("stage_transactions", TestType.STAGECOUNT)].result == TestResult.OK
        for tc in sales_tr.testcase_results:
            assert tc.status == TestStatus.FINISHED

        # 4. Reports persisted with correct results
        report_driver = verify_di.report_driver()

        payments_tr_reports = report_driver.list_testrun_reports(
            domain="payments",
        )
        sales_tr_reports = report_driver.list_testrun_reports(
            domain="sales",
        )
        assert len(payments_tr_reports) == 1
        assert len(sales_tr_reports) == 1

        payments_tc_reports = report_driver.list_testcase_reports(
            domain="payments",
        )
        sales_tc_reports = report_driver.list_testcase_reports(
            domain="sales",
        )
        assert len(payments_tc_reports) == 6
        assert len(sales_tc_reports) == 6

        for report in payments_tc_reports:
            assert report.domain == "payments"
            assert report.result in (
                TestResult.OK.value,
                TestResult.NOK.value,
            )

        for report in sales_tc_reports:
            assert report.domain == "sales"
            assert report.result in (
                TestResult.OK.value,
                TestResult.NOK.value,
            )

        nok = TestResult.NOK.value
        assert len([r for r in payments_tc_reports if r.result == nok]) == 1
        assert len([r for r in sales_tc_reports if r.result == nok]) == 1

        # 5. No cross-contamination
        for report in payments_tc_reports:
            assert report.domain == "payments"
        for report in sales_tc_reports:
            assert report.domain == "sales"
