"""
End-to-end integration test for CliApp with DemoBackend — sales domain only.

Tests the full pipeline: domain config loading, testset loading, specification
finding, test execution, and report generation.

Test design leverages deliberate data quality issues in prepare_demo_data.py:
  - sales: core_customer_transactions filters out africa region,
    causing a compare mismatch (NOK).

Demo artifacts (specs, configs, testsets) are generated by
prepare_demo_artifacts.py and read from disk via LocalUserStorage.

The payments domain is tested separately in test_http_app.py.

DO NOT USE PAYMENTS DOMAIN HERE TO NOT MIX DATA BETWEEN FIXTURES!!!
"""

from tests.conftest import DemoData
from src.apps.cli_app import CliApp
from src.apps.cli_di import CliDependencyInjector
from src.config import Config
from src.dtos import (
    TestResult,
    TestStatus,
    TestType,
)


class TestCliAppE2E:
    def test_sales_domain_execution(self, demo_data: DemoData):
        config = Config(
            DATATESTER_DATA_PLATFORM="DEMO",
            DATATESTER_USER_STORAGE_ENGINE="LOCAL",
            DATATESTER_INTERNAL_STORAGE_LOCATION=demo_data.internal_location,
            DATATESTER_DEMO_RAW_PATH=demo_data.raw_path,
            DATATESTER_DEMO_DB_PATH=demo_data.db_path,
        )

        # --- Execute sales domain ---
        app = CliApp(config)
        app.run_tests("sales", "sales_validation")

        # --- Verify using fresh DI ---
        verify_di = CliDependencyInjector(config)

        # 1. Testruns persisted
        tr_driver = verify_di.testrun_driver()
        sales_trs = tr_driver.list_testruns(domain="sales")
        assert len(sales_trs) == 1

        # 2. Sales testrun: 6 testcases, overall NOK
        #    NOK because core_customer_transactions COMPARE fails (africa)
        sales_tr = sales_trs[0]
        assert len(sales_tr.testcase_results) == 6
        assert sales_tr.result == TestResult.NOK
        assert sales_tr.status == TestStatus.FINISHED

        sr = {(tc.testobject.name, tc.testtype): tc for tc in sales_tr.testcase_results}
        assert sr[("stage_customers", TestType.SCHEMA)].result == TestResult.OK
        assert sr[("stage_transactions", TestType.SCHEMA)].result == TestResult.OK
        assert (
            sr[("core_customer_transactions", TestType.ROWCOUNT)].result == TestResult.OK
        )
        assert (
            sr[("core_customer_transactions", TestType.COMPARE)].result == TestResult.NOK
        )
        assert sr[("stage_customers", TestType.STAGECOUNT)].result == TestResult.OK
        assert sr[("stage_transactions", TestType.STAGECOUNT)].result == TestResult.OK
        for tc in sales_tr.testcase_results:
            assert tc.status == TestStatus.FINISHED

        # 3. Reports persisted with correct results
        report_driver = verify_di.report_driver()

        sales_tr_reports = report_driver.list_testrun_reports(domain="sales")
        assert len(sales_tr_reports) == 1

        sales_tc_reports = report_driver.list_testcase_reports(domain="sales")
        assert len(sales_tc_reports) == 6

        for report in sales_tc_reports:
            assert report.domain == "sales"
            assert report.result in (
                TestResult.OK.value,
                TestResult.NOK.value,
            )

        nok = TestResult.NOK.value
        assert len([r for r in sales_tc_reports if r.result == nok]) == 1
