name: Merge-PR

on: pull_request

permissions:
  pull-requests: write  
  contents: write

jobs:

  merge-pr:
    name: Merge-PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: merge
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # requires GitHub action settings to allow auto-merge PRs
        run: |
          gh pr merge --auto --rebase $PR_URL