name: Merge

on: pull_request

jobs:

  merge-pr:
    name: Merge-PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: merge
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # requires GitHub action settings to allow auto-merge PRs
      run: |
        gh pr merge master --auto