# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test

on: push

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # required by coverage action to comment coverage on PRs
      contents: write  # required by coverage action to push to coverage-commend-action branch
    steps:
    - uses: actions/checkout@v4

    - name: set up python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: linting
      # ruff config is defined in pyproject.toml
      run: |
        # stop the build if there are Python syntax errors or undefined names
        ruff check

    - name: typechecks
      # mypy config is defined in pyproject.toml
      run: |
        mypy

    - name: tests
      # coverage and pytest configuration are in pyproject.toml
      run: |
        coverage run
        coverage report

    - name: coverage report
      # see https://github.com/marketplace/actions/python-coverage-comment
      uses: py-cov-action/python-coverage-comment-action@v3
      with:
        GITHUB_TOKEN: ${{ github.token }}
        MINIMUM_GREEN: 90
        MINIMUM_ORANGE: 70
