# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more info see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test

on: push

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # required by coverage action to comment coverage on PRs
      contents: write  # required by coverage action to push to coverage-commend-action branch
    steps:
    - uses: actions/checkout@v4

    - name: set up uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.6.1"

    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: install dependencies
      run: |
        uv sync --locked --dev

    - name: linting
      # ruff config is defined in pyproject.toml
      run: |
        uv run ruff check --fix  # stop the build if there are errors

    - name: typechecks
      # mypy config is defined in pyproject.toml
      run: |
        uv run mypy

    - name: enforce import contracts
      run: |
        uv run lint-imports

    - name: tests
      # coverage and pytest configuration are in pyproject.toml
      run: |
        uv run coverage run
        uv run coverage report

    - name: coverage report
      uses: py-cov-action/python-coverage-comment-action@v3
      with:
        GITHUB_TOKEN: ${{ github.token }}
        MINIMUM_GREEN: 90
        MINIMUM_ORANGE: 70

    - name: Create-PR
      if: github.ref != master
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # requires GitHub action settings to allow auto-create PRs
      run: |
        gh pr create --title "Auto-PR" --body "Auto-PR" --base master --head adanilevich:$(git branch --show-current)

